/* tslint:disable */
/* eslint-disable */
/**
 * DrinkFood_API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ResponseModel,
} from '../models/index';
import {
    ResponseModelFromJSON,
    ResponseModelToJSON,
} from '../models/index';

export interface ApiDrinkFoodGetDrinkFoodListStoreIDGetRequest {
    storeID: string;
}

/**
 * 
 */
export class DrinkFoodApi extends runtime.BaseAPI {

    /**
     */
    async apiDrinkFoodGetDrinkFoodListStoreIDGetRaw(requestParameters: ApiDrinkFoodGetDrinkFoodListStoreIDGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseModel>> {
        if (requestParameters.storeID === null || requestParameters.storeID === undefined) {
            throw new runtime.RequiredError('storeID','Required parameter requestParameters.storeID was null or undefined when calling apiDrinkFoodGetDrinkFoodListStoreIDGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/DrinkFood/GetDrinkFoodList/{StoreID}`.replace(`{${"StoreID"}}`, encodeURIComponent(String(requestParameters.storeID))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseModelFromJSON(jsonValue));
    }

    /**
     */
    async apiDrinkFoodGetDrinkFoodListStoreIDGet(requestParameters: ApiDrinkFoodGetDrinkFoodListStoreIDGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseModel> {
        const response = await this.apiDrinkFoodGetDrinkFoodListStoreIDGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
