/* tslint:disable */
/* eslint-disable */
/**
 * 訂餐系統
 * 系統API規格說明
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ResponseInfoCardModel,
  ResponseTodayOrderModel,
} from '../models/index';
import {
    ResponseInfoCardModelFromJSON,
    ResponseInfoCardModelToJSON,
    ResponseTodayOrderModelFromJSON,
    ResponseTodayOrderModelToJSON,
} from '../models/index';

/**
 * 
 */
export class HomeApi extends runtime.BaseAPI {

    /**
     */
    async apiHomeGetInfoCardGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseInfoCardModel>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/Home/GetInfoCard`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseInfoCardModelFromJSON(jsonValue));
    }

    /**
     */
    async apiHomeGetInfoCardGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseInfoCardModel> {
        const response = await this.apiHomeGetInfoCardGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async apiHomeGetTodayOrderGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ResponseTodayOrderModel>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/Home/GetTodayOrder`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ResponseTodayOrderModelFromJSON));
    }

    /**
     */
    async apiHomeGetTodayOrderGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ResponseTodayOrderModel>> {
        const response = await this.apiHomeGetTodayOrderGetRaw(initOverrides);
        return await response.value();
    }

}
