/* tslint:disable */
/* eslint-disable */
/**
 * 訂餐系統
 * 系統API規格說明
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  RequestLoginModel,
  ResponseLoginModel,
} from '../models/index';
import {
    RequestLoginModelFromJSON,
    RequestLoginModelToJSON,
    ResponseLoginModelFromJSON,
    ResponseLoginModelToJSON,
} from '../models/index';

export interface ApiLoginLoginPostRequest {
    requestLoginModel?: RequestLoginModel;
}

/**
 * 
 */
export class LoginApi extends runtime.BaseAPI {

    /**
     */
    async apiLoginLoginPostRaw(requestParameters: ApiLoginLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseLoginModel>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/Login/Login`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RequestLoginModelToJSON(requestParameters.requestLoginModel),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseLoginModelFromJSON(jsonValue));
    }

    /**
     */
    async apiLoginLoginPost(requestParameters: ApiLoginLoginPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseLoginModel> {
        const response = await this.apiLoginLoginPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
