/* tslint:disable */
/* eslint-disable */
/**
 * 訂餐系統
 * 系統API規格說明
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Asn1GeneralizedTime
 */
export interface Asn1GeneralizedTime {
    /**
     * 
     * @type {string}
     * @memberof Asn1GeneralizedTime
     */
    TimeString?: string | null;
}

/**
 * Check if a given object implements the Asn1GeneralizedTime interface.
 */
export function instanceOfAsn1GeneralizedTime(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function Asn1GeneralizedTimeFromJSON(json: any): Asn1GeneralizedTime {
    return Asn1GeneralizedTimeFromJSONTyped(json, false);
}

export function Asn1GeneralizedTimeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Asn1GeneralizedTime {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'TimeString': !exists(json, 'TimeString') ? undefined : json['TimeString'],
    };
}

export function Asn1GeneralizedTimeToJSON(value?: Asn1GeneralizedTime | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'TimeString': value.TimeString,
    };
}

