/* tslint:disable */
/* eslint-disable */
/**
 * 訂餐系統
 * 系統API規格說明
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DerObjectIdentifier
 */
export interface DerObjectIdentifier {
    /**
     * 
     * @type {string}
     * @memberof DerObjectIdentifier
     */
    readonly Id?: string | null;
}

/**
 * Check if a given object implements the DerObjectIdentifier interface.
 */
export function instanceOfDerObjectIdentifier(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DerObjectIdentifierFromJSON(json: any): DerObjectIdentifier {
    return DerObjectIdentifierFromJSONTyped(json, false);
}

export function DerObjectIdentifierFromJSONTyped(json: any, ignoreDiscriminator: boolean): DerObjectIdentifier {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'Id': !exists(json, 'Id') ? undefined : json['Id'],
    };
}

export function DerObjectIdentifierToJSON(value?: DerObjectIdentifier | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}

