/* tslint:disable */
/* eslint-disable */
/**
 * 訂餐系統
 * 系統API規格說明
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ViewDrinkFoodModel } from './ViewDrinkFoodModel';
import {
    ViewDrinkFoodModelFromJSON,
    ViewDrinkFoodModelFromJSONTyped,
    ViewDrinkFoodModelToJSON,
} from './ViewDrinkFoodModel';

/**
 * 
 * @export
 * @interface GroupDrinkFoodModel
 */
export interface GroupDrinkFoodModel {
    /**
     * 
     * @type {string}
     * @memberof GroupDrinkFoodModel
     */
    DrinkFoodTypeID?: string;
    /**
     * 
     * @type {string}
     * @memberof GroupDrinkFoodModel
     */
    DrinkFoodTypeDesc?: string | null;
    /**
     * 
     * @type {Array<ViewDrinkFoodModel>}
     * @memberof GroupDrinkFoodModel
     */
    DrinkFoodList?: Array<ViewDrinkFoodModel> | null;
}

/**
 * Check if a given object implements the GroupDrinkFoodModel interface.
 */
export function instanceOfGroupDrinkFoodModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GroupDrinkFoodModelFromJSON(json: any): GroupDrinkFoodModel {
    return GroupDrinkFoodModelFromJSONTyped(json, false);
}

export function GroupDrinkFoodModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupDrinkFoodModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'DrinkFoodTypeID': !exists(json, 'DrinkFoodTypeID') ? undefined : json['DrinkFoodTypeID'],
        'DrinkFoodTypeDesc': !exists(json, 'DrinkFoodTypeDesc') ? undefined : json['DrinkFoodTypeDesc'],
        'DrinkFoodList': !exists(json, 'DrinkFoodList') ? undefined : (json['DrinkFoodList'] === null ? null : (json['DrinkFoodList'] as Array<any>).map(ViewDrinkFoodModelFromJSON)),
    };
}

export function GroupDrinkFoodModelToJSON(value?: GroupDrinkFoodModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'DrinkFoodTypeID': value.DrinkFoodTypeID,
        'DrinkFoodTypeDesc': value.DrinkFoodTypeDesc,
        'DrinkFoodList': value.DrinkFoodList === undefined ? undefined : (value.DrinkFoodList === null ? null : (value.DrinkFoodList as Array<any>).map(ViewDrinkFoodModelToJSON)),
    };
}

