/* tslint:disable */
/* eslint-disable */
/**
 * DrinkFood_API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ViewOrderDetail } from './ViewOrderDetail';
import {
    ViewOrderDetailFromJSON,
    ViewOrderDetailFromJSONTyped,
    ViewOrderDetailToJSON,
} from './ViewOrderDetail';

/**
 * 
 * @export
 * @interface GroupOrderDetailModel
 */
export interface GroupOrderDetailModel {
    /**
     * 
     * @type {string}
     * @memberof GroupOrderDetailModel
     */
    Name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof GroupOrderDetailModel
     */
    TotalPrice?: number;
    /**
     * 
     * @type {number}
     * @memberof GroupOrderDetailModel
     */
    TotalQuantity?: number;
    /**
     * 
     * @type {Array<ViewOrderDetail>}
     * @memberof GroupOrderDetailModel
     */
    OrderDetailList?: Array<ViewOrderDetail> | null;
}

/**
 * Check if a given object implements the GroupOrderDetailModel interface.
 */
export function instanceOfGroupOrderDetailModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GroupOrderDetailModelFromJSON(json: any): GroupOrderDetailModel {
    return GroupOrderDetailModelFromJSONTyped(json, false);
}

export function GroupOrderDetailModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupOrderDetailModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'Name': !exists(json, 'Name') ? undefined : json['Name'],
        'TotalPrice': !exists(json, 'TotalPrice') ? undefined : json['TotalPrice'],
        'TotalQuantity': !exists(json, 'TotalQuantity') ? undefined : json['TotalQuantity'],
        'OrderDetailList': !exists(json, 'OrderDetailList') ? undefined : (json['OrderDetailList'] === null ? null : (json['OrderDetailList'] as Array<any>).map(ViewOrderDetailFromJSON)),
    };
}

export function GroupOrderDetailModelToJSON(value?: GroupOrderDetailModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Name': value.Name,
        'TotalPrice': value.TotalPrice,
        'TotalQuantity': value.TotalQuantity,
        'OrderDetailList': value.OrderDetailList === undefined ? undefined : (value.OrderDetailList === null ? null : (value.OrderDetailList as Array<any>).map(ViewOrderDetailToJSON)),
    };
}

