/* tslint:disable */
/* eslint-disable */
/**
 * 訂餐系統
 * 系統API規格說明
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InfoCardDataModel
 */
export interface InfoCardDataModel {
    /**
     * 
     * @type {string}
     * @memberof InfoCardDataModel
     */
    Title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InfoCardDataModel
     */
    Main?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InfoCardDataModel
     */
    Info?: string | null;
}

/**
 * Check if a given object implements the InfoCardDataModel interface.
 */
export function instanceOfInfoCardDataModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function InfoCardDataModelFromJSON(json: any): InfoCardDataModel {
    return InfoCardDataModelFromJSONTyped(json, false);
}

export function InfoCardDataModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): InfoCardDataModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'Title': !exists(json, 'Title') ? undefined : json['Title'],
        'Main': !exists(json, 'Main') ? undefined : json['Main'],
        'Info': !exists(json, 'Info') ? undefined : json['Info'],
    };
}

export function InfoCardDataModelToJSON(value?: InfoCardDataModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Title': value.Title,
        'Main': value.Main,
        'Info': value.Info,
    };
}

