/* tslint:disable */
/* eslint-disable */
/**
 * DrinkFood_API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestCreateAccountModel
 */
export interface RequestCreateAccountModel {
    /**
     * 
     * @type {string}
     * @memberof RequestCreateAccountModel
     */
    brief?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RequestCreateAccountModel
     */
    lunchDefaultPayment?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RequestCreateAccountModel
     */
    drinkDefaultPayment?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof RequestCreateAccountModel
     */
    lunchNotify?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RequestCreateAccountModel
     */
    drinkNotify?: boolean;
    /**
     * 
     * @type {number}
     * @memberof RequestCreateAccountModel
     */
    closeNotify?: number;
    /**
     * 
     * @type {string}
     * @memberof RequestCreateAccountModel
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RequestCreateAccountModel
     */
    email?: string | null;
}

/**
 * Check if a given object implements the RequestCreateAccountModel interface.
 */
export function instanceOfRequestCreateAccountModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RequestCreateAccountModelFromJSON(json: any): RequestCreateAccountModel {
    return RequestCreateAccountModelFromJSONTyped(json, false);
}

export function RequestCreateAccountModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestCreateAccountModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'brief': !exists(json, 'Brief') ? undefined : json['Brief'],
        'lunchDefaultPayment': !exists(json, 'LunchDefaultPayment') ? undefined : json['LunchDefaultPayment'],
        'drinkDefaultPayment': !exists(json, 'DrinkDefaultPayment') ? undefined : json['DrinkDefaultPayment'],
        'lunchNotify': !exists(json, 'LunchNotify') ? undefined : json['LunchNotify'],
        'drinkNotify': !exists(json, 'DrinkNotify') ? undefined : json['DrinkNotify'],
        'closeNotify': !exists(json, 'CloseNotify') ? undefined : json['CloseNotify'],
        'name': !exists(json, 'Name') ? undefined : json['Name'],
        'email': !exists(json, 'Email') ? undefined : json['Email'],
    };
}

export function RequestCreateAccountModelToJSON(value?: RequestCreateAccountModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Brief': value.brief,
        'LunchDefaultPayment': value.lunchDefaultPayment,
        'DrinkDefaultPayment': value.drinkDefaultPayment,
        'LunchNotify': value.lunchNotify,
        'DrinkNotify': value.drinkNotify,
        'CloseNotify': value.closeNotify,
        'Name': value.name,
        'Email': value.email,
    };
}

