/* tslint:disable */
/* eslint-disable */
/**
 * DrinkFood_API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestPostOrderModel
 */
export interface RequestPostOrderModel {
    /**
     * 
     * @type {string}
     * @memberof RequestPostOrderModel
     */
    officeID?: string;
    /**
     * 
     * @type {string}
     * @memberof RequestPostOrderModel
     */
    createAccountID?: string;
    /**
     * 
     * @type {string}
     * @memberof RequestPostOrderModel
     */
    storeID?: string;
    /**
     * 
     * @type {string}
     * @memberof RequestPostOrderModel
     */
    orderTypeID?: string;
    /**
     * 
     * @type {Date}
     * @memberof RequestPostOrderModel
     */
    arrivalTime?: Date;
    /**
     * 
     * @type {Date}
     * @memberof RequestPostOrderModel
     */
    openTime?: Date;
    /**
     * 
     * @type {Date}
     * @memberof RequestPostOrderModel
     */
    closeTime?: Date;
}

/**
 * Check if a given object implements the RequestPostOrderModel interface.
 */
export function instanceOfRequestPostOrderModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RequestPostOrderModelFromJSON(json: any): RequestPostOrderModel {
    return RequestPostOrderModelFromJSONTyped(json, false);
}

export function RequestPostOrderModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestPostOrderModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'officeID': !exists(json, 'OfficeID') ? undefined : json['OfficeID'],
        'createAccountID': !exists(json, 'CreateAccountID') ? undefined : json['CreateAccountID'],
        'storeID': !exists(json, 'StoreID') ? undefined : json['StoreID'],
        'orderTypeID': !exists(json, 'OrderTypeID') ? undefined : json['OrderTypeID'],
        'arrivalTime': !exists(json, 'ArrivalTime') ? undefined : (new Date(json['ArrivalTime'])),
        'openTime': !exists(json, 'OpenTime') ? undefined : (new Date(json['OpenTime'])),
        'closeTime': !exists(json, 'CloseTime') ? undefined : (new Date(json['CloseTime'])),
    };
}

export function RequestPostOrderModelToJSON(value?: RequestPostOrderModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'OfficeID': value.officeID,
        'CreateAccountID': value.createAccountID,
        'StoreID': value.storeID,
        'OrderTypeID': value.orderTypeID,
        'ArrivalTime': value.arrivalTime === undefined ? undefined : (value.arrivalTime.toISOString()),
        'OpenTime': value.openTime === undefined ? undefined : (value.openTime.toISOString()),
        'CloseTime': value.closeTime === undefined ? undefined : (value.closeTime.toISOString()),
    };
}

