/* tslint:disable */
/* eslint-disable */
/**
 * 訂餐系統
 * 系統API規格說明
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestBindLineModel
 */
export interface RequestBindLineModel {
    /**
     * 
     * @type {string}
     * @memberof RequestBindLineModel
     */
    code?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RequestBindLineModel
     */
    state?: string;
}

/**
 * Check if a given object implements the RequestBindLineModel interface.
 */
export function instanceOfRequestBindLineModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RequestBindLineModelFromJSON(json: any): RequestBindLineModel {
    return RequestBindLineModelFromJSONTyped(json, false);
}

export function RequestBindLineModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestBindLineModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'state': !exists(json, 'state') ? undefined : json['state'],
    };
}

export function RequestBindLineModelToJSON(value?: RequestBindLineModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'state': value.state,
    };
}

