/* tslint:disable */
/* eslint-disable */
/**
 * DrinkFood_API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestPutPaymentModel
 */
export interface RequestPutPaymentModel {
    /**
     * 
     * @type {string}
     * @memberof RequestPutPaymentModel
     */
    PaymentID?: string | null;
}

/**
 * Check if a given object implements the RequestPutPaymentModel interface.
 */
export function instanceOfRequestPutPaymentModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RequestPutPaymentModelFromJSON(json: any): RequestPutPaymentModel {
    return RequestPutPaymentModelFromJSONTyped(json, false);
}

export function RequestPutPaymentModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestPutPaymentModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'PaymentID': !exists(json, 'PaymentID') ? undefined : json['PaymentID'],
    };
}

export function RequestPutPaymentModelToJSON(value?: RequestPutPaymentModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'PaymentID': value.PaymentID,
    };
}

