/* tslint:disable */
/* eslint-disable */
/**
 * DrinkFood_API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestCreateAccountModel
 */
export interface RequestCreateAccountModel {
    /**
     * 
     * @type {string}
     * @memberof RequestCreateAccountModel
     */
    Brief?: string;
    /**
     * 
     * @type {string}
     * @memberof RequestCreateAccountModel
     */
    LunchDefaultPayment?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RequestCreateAccountModel
     */
    DrinkDefaultPayment?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof RequestCreateAccountModel
     */
    LunchNotify: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RequestCreateAccountModel
     */
    DrinkNotify: boolean;
    /**
     * 
     * @type {number}
     * @memberof RequestCreateAccountModel
     */
    CloseNotify?: number;
    /**
     * 
     * @type {string}
     * @memberof RequestCreateAccountModel
     */
    Name: string;
    /**
     * 
     * @type {string}
     * @memberof RequestCreateAccountModel
     */
    Email: string;
}

/**
 * Check if a given object implements the RequestCreateAccountModel interface.
 */
export function instanceOfRequestCreateAccountModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RequestCreateAccountModelFromJSON(json: any): RequestCreateAccountModel {
    return RequestCreateAccountModelFromJSONTyped(json, false);
}

export function RequestCreateAccountModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestCreateAccountModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'Brief': !exists(json, 'Brief') ? undefined : json['Brief'],
        'LunchDefaultPayment': !exists(json, 'LunchDefaultPayment') ? undefined : json['LunchDefaultPayment'],
        'DrinkDefaultPayment': !exists(json, 'DrinkDefaultPayment') ? undefined : json['DrinkDefaultPayment'],
        'LunchNotify': !exists(json, 'LunchNotify') ? undefined : json['LunchNotify'],
        'DrinkNotify': !exists(json, 'DrinkNotify') ? undefined : json['DrinkNotify'],
        'CloseNotify': !exists(json, 'CloseNotify') ? undefined : json['CloseNotify'],
        'Name': !exists(json, 'Name') ? undefined : json['Name'],
        'Email': !exists(json, 'Email') ? undefined : json['Email'],
    };
}

export function RequestCreateAccountModelToJSON(value?: RequestCreateAccountModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Brief': value.Brief,
        'LunchDefaultPayment': value.LunchDefaultPayment,
        'DrinkDefaultPayment': value.DrinkDefaultPayment,
        'LunchNotify': value.LunchNotify,
        'DrinkNotify': value.DrinkNotify,
        'CloseNotify': value.CloseNotify,
        'Name': value.Name,
        'Email': value.Email,
    };
}

