/* tslint:disable */
/* eslint-disable */
/**
 * DrinkFood_API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestPutPaymentDateTimeModel
 */
export interface RequestPutPaymentDateTimeModel {
    /**
     * 
     * @type {Date}
     * @memberof RequestPutPaymentDateTimeModel
     */
    paymentDateTime?: Date | null;
}

/**
 * Check if a given object implements the RequestPutPaymentDateTimeModel interface.
 */
export function instanceOfRequestPutPaymentDateTimeModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RequestPutPaymentDateTimeModelFromJSON(json: any): RequestPutPaymentDateTimeModel {
    return RequestPutPaymentDateTimeModelFromJSONTyped(json, false);
}

export function RequestPutPaymentDateTimeModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestPutPaymentDateTimeModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'paymentDateTime': !exists(json, 'PaymentDateTime') ? undefined : (json['PaymentDateTime'] === null ? null : new Date(json['PaymentDateTime'])),
    };
}

export function RequestPutPaymentDateTimeModelToJSON(value?: RequestPutPaymentDateTimeModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'PaymentDateTime': value.paymentDateTime === undefined ? undefined : (value.paymentDateTime === null ? null : value.paymentDateTime.toISOString()),
    };
}

