/* tslint:disable */
/* eslint-disable */
/**
 * DrinkFood_API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestPostOrderModel
 */
export interface RequestPostOrderModel {
    /**
     * 
     * @type {string}
     * @memberof RequestPostOrderModel
     */
    OfficeID?: string;
    /**
     * 
     * @type {string}
     * @memberof RequestPostOrderModel
     */
    CreateAccountID?: string;
    /**
     * 
     * @type {string}
     * @memberof RequestPostOrderModel
     */
    StoreID?: string;
    /**
     * 
     * @type {string}
     * @memberof RequestPostOrderModel
     */
    TypeID?: string;
    /**
     * 
     * @type {Date}
     * @memberof RequestPostOrderModel
     */
    ArrivalTime?: Date | undefined;
    /**
     * 
     * @type {Date}
     * @memberof RequestPostOrderModel
     */
    OpenTime?: Date | undefined;
    /**
     * 
     * @type {Date}
     * @memberof RequestPostOrderModel
     */
    CloseTime?: Date | undefined;
    /**
     * 
     * @type {boolean}
     * @memberof RequestPostOrderModel
     */
    IsPublic: boolean;
}

/**
 * Check if a given object implements the RequestPostOrderModel interface.
 */
export function instanceOfRequestPostOrderModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RequestPostOrderModelFromJSON(json: any): RequestPostOrderModel {
    return RequestPostOrderModelFromJSONTyped(json, false);
}

export function RequestPostOrderModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestPostOrderModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'OfficeID': !exists(json, 'OfficeID') ? undefined : json['OfficeID'],
        'CreateAccountID': !exists(json, 'CreateAccountID') ? undefined : json['CreateAccountID'],
        'StoreID': !exists(json, 'StoreID') ? undefined : json['StoreID'],
        'TypeID': !exists(json, 'TypeID') ? undefined : json['TypeID'],
        'ArrivalTime': !exists(json, 'ArrivalTime') ? undefined : (new Date(json['ArrivalTime'])),
        'OpenTime': !exists(json, 'OpenTime') ? undefined : (new Date(json['OpenTime'])),
        'CloseTime': !exists(json, 'CloseTime') ? undefined : (new Date(json['CloseTime'])),
        'IsPublic': !exists(json, 'IsPublic') ? undefined : json['IsPublic'],
    };
}

export function RequestPostOrderModelToJSON(value?: RequestPostOrderModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'OfficeID': value.OfficeID,
        'CreateAccountID': value.CreateAccountID,
        'StoreID': value.StoreID,
        'TypeID': value.TypeID,
        'ArrivalTime': value.ArrivalTime === undefined ? undefined : (value.ArrivalTime.toISOString()),
        'OpenTime': value.OpenTime === undefined ? undefined : (value.OpenTime.toISOString()),
        'CloseTime': value.CloseTime === undefined ? undefined : (value.CloseTime.toISOString()),
        'IsPublic': value.IsPublic,
    };
}

