/* tslint:disable */
/* eslint-disable */
/**
 * DrinkFood_API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestPostOrderDetailModel
 */
export interface RequestPostOrderDetailModel {
    /**
     * 
     * @type {string}
     * @memberof RequestPostOrderDetailModel
     */
    oDOrderId?: string;
    /**
     * 
     * @type {string}
     * @memberof RequestPostOrderDetailModel
     */
    oDDrinkFoodId?: string;
    /**
     * 
     * @type {string}
     * @memberof RequestPostOrderDetailModel
     */
    oDSugarId?: string;
    /**
     * 
     * @type {string}
     * @memberof RequestPostOrderDetailModel
     */
    oDIceId?: string;
    /**
     * 
     * @type {string}
     * @memberof RequestPostOrderDetailModel
     */
    oDSizeId?: string;
    /**
     * 
     * @type {string}
     * @memberof RequestPostOrderDetailModel
     */
    oDAccountId?: string;
    /**
     * 
     * @type {string}
     * @memberof RequestPostOrderDetailModel
     */
    oDRemark?: string | null;
}

/**
 * Check if a given object implements the RequestPostOrderDetailModel interface.
 */
export function instanceOfRequestPostOrderDetailModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RequestPostOrderDetailModelFromJSON(json: any): RequestPostOrderDetailModel {
    return RequestPostOrderDetailModelFromJSONTyped(json, false);
}

export function RequestPostOrderDetailModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestPostOrderDetailModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'oDOrderId': !exists(json, 'OD_order_id') ? undefined : json['OD_order_id'],
        'oDDrinkFoodId': !exists(json, 'OD_drink_food_id') ? undefined : json['OD_drink_food_id'],
        'oDSugarId': !exists(json, 'OD_sugar_id') ? undefined : json['OD_sugar_id'],
        'oDIceId': !exists(json, 'OD_ice_id') ? undefined : json['OD_ice_id'],
        'oDSizeId': !exists(json, 'OD_size_id') ? undefined : json['OD_size_id'],
        'oDAccountId': !exists(json, 'OD_account_id') ? undefined : json['OD_account_id'],
        'oDRemark': !exists(json, 'OD_remark') ? undefined : json['OD_remark'],
    };
}

export function RequestPostOrderDetailModelToJSON(value?: RequestPostOrderDetailModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'OD_order_id': value.oDOrderId,
        'OD_drink_food_id': value.oDDrinkFoodId,
        'OD_sugar_id': value.oDSugarId,
        'OD_ice_id': value.oDIceId,
        'OD_size_id': value.oDSizeId,
        'OD_account_id': value.oDAccountId,
        'OD_remark': value.oDRemark,
    };
}

