/* tslint:disable */
/* eslint-disable */
/**
 * DrinkFood_API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestUpdateProfileModel
 */
export interface RequestUpdateProfileModel {
    /**
     * 
     * @type {string}
     * @memberof RequestUpdateProfileModel
     */
    brief?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RequestUpdateProfileModel
     */
    lunchDefaultPayment?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RequestUpdateProfileModel
     */
    drinkDefaultPayment?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof RequestUpdateProfileModel
     */
    lunchNotify?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RequestUpdateProfileModel
     */
    drinkNotify?: boolean;
    /**
     * 
     * @type {number}
     * @memberof RequestUpdateProfileModel
     */
    closeNotify?: number;
}

/**
 * Check if a given object implements the RequestUpdateProfileModel interface.
 */
export function instanceOfRequestUpdateProfileModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RequestUpdateProfileModelFromJSON(json: any): RequestUpdateProfileModel {
    return RequestUpdateProfileModelFromJSONTyped(json, false);
}

export function RequestUpdateProfileModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestUpdateProfileModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'brief': !exists(json, 'Brief') ? undefined : json['Brief'],
        'lunchDefaultPayment': !exists(json, 'LunchDefaultPayment') ? undefined : json['LunchDefaultPayment'],
        'drinkDefaultPayment': !exists(json, 'DrinkDefaultPayment') ? undefined : json['DrinkDefaultPayment'],
        'lunchNotify': !exists(json, 'LunchNotify') ? undefined : json['LunchNotify'],
        'drinkNotify': !exists(json, 'DrinkNotify') ? undefined : json['DrinkNotify'],
        'closeNotify': !exists(json, 'CloseNotify') ? undefined : json['CloseNotify'],
    };
}

export function RequestUpdateProfileModelToJSON(value?: RequestUpdateProfileModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Brief': value.brief,
        'LunchDefaultPayment': value.lunchDefaultPayment,
        'DrinkDefaultPayment': value.drinkDefaultPayment,
        'LunchNotify': value.lunchNotify,
        'DrinkNotify': value.drinkNotify,
        'CloseNotify': value.closeNotify,
    };
}

