/* tslint:disable */
/* eslint-disable */
/**
 * DrinkFood_API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestPutCloseTimeModel
 */
export interface RequestPutCloseTimeModel {
    /**
     * 
     * @type {Date}
     * @memberof RequestPutCloseTimeModel
     */
    CloseTime?: Date;
}

/**
 * Check if a given object implements the RequestPutCloseTimeModel interface.
 */
export function instanceOfRequestPutCloseTimeModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RequestPutCloseTimeModelFromJSON(json: any): RequestPutCloseTimeModel {
    return RequestPutCloseTimeModelFromJSONTyped(json, false);
}

export function RequestPutCloseTimeModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestPutCloseTimeModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'CloseTime': !exists(json, 'CloseTime') ? undefined : (new Date(json['CloseTime'])),
    };
}

export function RequestPutCloseTimeModelToJSON(value?: RequestPutCloseTimeModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'CloseTime': value.CloseTime === undefined ? undefined : (value.CloseTime.toISOString()),
    };
}

