/* tslint:disable */
/* eslint-disable */
/**
 * 訂餐系統
 * 系統API規格說明
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestPutArrivalTimeModel
 */
export interface RequestPutArrivalTimeModel {
    /**
     * 
     * @type {Date}
     * @memberof RequestPutArrivalTimeModel
     */
    ArrivalTime?: Date;
}

/**
 * Check if a given object implements the RequestPutArrivalTimeModel interface.
 */
export function instanceOfRequestPutArrivalTimeModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RequestPutArrivalTimeModelFromJSON(json: any): RequestPutArrivalTimeModel {
    return RequestPutArrivalTimeModelFromJSONTyped(json, false);
}

export function RequestPutArrivalTimeModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestPutArrivalTimeModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ArrivalTime': !exists(json, 'ArrivalTime') ? undefined : (new Date(json['ArrivalTime'])),
    };
}

export function RequestPutArrivalTimeModelToJSON(value?: RequestPutArrivalTimeModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ArrivalTime': value.ArrivalTime === undefined ? undefined : (value.ArrivalTime.toISOString()),
    };
}

