/* tslint:disable */
/* eslint-disable */
/**
 * DrinkFood_API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestPutOrderTimeModel
 */
export interface RequestPutOrderTimeModel {
    /**
     * 
     * @type {Date}
     * @memberof RequestPutOrderTimeModel
     */
    drinkTime?: Date;
    /**
     * 
     * @type {Date}
     * @memberof RequestPutOrderTimeModel
     */
    closeTime?: Date;
}

/**
 * Check if a given object implements the RequestPutOrderTimeModel interface.
 */
export function instanceOfRequestPutOrderTimeModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RequestPutOrderTimeModelFromJSON(json: any): RequestPutOrderTimeModel {
    return RequestPutOrderTimeModelFromJSONTyped(json, false);
}

export function RequestPutOrderTimeModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestPutOrderTimeModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'drinkTime': !exists(json, 'DrinkTime') ? undefined : (new Date(json['DrinkTime'])),
        'closeTime': !exists(json, 'CloseTime') ? undefined : (new Date(json['CloseTime'])),
    };
}

export function RequestPutOrderTimeModelToJSON(value?: RequestPutOrderTimeModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'DrinkTime': value.drinkTime === undefined ? undefined : (value.drinkTime.toISOString()),
        'CloseTime': value.closeTime === undefined ? undefined : (value.closeTime.toISOString()),
    };
}

