/* tslint:disable */
/* eslint-disable */
/**
 * 訂餐系統
 * 系統API規格說明
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Asn1GeneralizedTime } from './Asn1GeneralizedTime';
import {
    Asn1GeneralizedTimeFromJSON,
    Asn1GeneralizedTimeFromJSONTyped,
    Asn1GeneralizedTimeToJSON,
} from './Asn1GeneralizedTime';
import type { DerInteger } from './DerInteger';
import {
    DerIntegerFromJSON,
    DerIntegerFromJSONTyped,
    DerIntegerToJSON,
} from './DerInteger';
import type { ResponderID } from './ResponderID';
import {
    ResponderIDFromJSON,
    ResponderIDFromJSONTyped,
    ResponderIDToJSON,
} from './ResponderID';
import type { X509Extensions } from './X509Extensions';
import {
    X509ExtensionsFromJSON,
    X509ExtensionsFromJSONTyped,
    X509ExtensionsToJSON,
} from './X509Extensions';

/**
 * 
 * @export
 * @interface ResponseData
 */
export interface ResponseData {
    /**
     * 
     * @type {DerInteger}
     * @memberof ResponseData
     */
    Version?: DerInteger;
    /**
     * 
     * @type {ResponderID}
     * @memberof ResponseData
     */
    ResponderID?: ResponderID;
    /**
     * 
     * @type {Asn1GeneralizedTime}
     * @memberof ResponseData
     */
    ProducedAt?: Asn1GeneralizedTime;
    /**
     * 
     * @type {Array<object>}
     * @memberof ResponseData
     */
    Responses?: Array<object> | null;
    /**
     * 
     * @type {X509Extensions}
     * @memberof ResponseData
     */
    ResponseExtensions?: X509Extensions;
}

/**
 * Check if a given object implements the ResponseData interface.
 */
export function instanceOfResponseData(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ResponseDataFromJSON(json: any): ResponseData {
    return ResponseDataFromJSONTyped(json, false);
}

export function ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'Version': !exists(json, 'Version') ? undefined : DerIntegerFromJSON(json['Version']),
        'ResponderID': !exists(json, 'ResponderID') ? undefined : ResponderIDFromJSON(json['ResponderID']),
        'ProducedAt': !exists(json, 'ProducedAt') ? undefined : Asn1GeneralizedTimeFromJSON(json['ProducedAt']),
        'Responses': !exists(json, 'Responses') ? undefined : json['Responses'],
        'ResponseExtensions': !exists(json, 'ResponseExtensions') ? undefined : X509ExtensionsFromJSON(json['ResponseExtensions']),
    };
}

export function ResponseDataToJSON(value?: ResponseData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Version': DerIntegerToJSON(value.Version),
        'ResponderID': ResponderIDToJSON(value.ResponderID),
        'ProducedAt': Asn1GeneralizedTimeToJSON(value.ProducedAt),
        'Responses': value.Responses,
        'ResponseExtensions': X509ExtensionsToJSON(value.ResponseExtensions),
    };
}

