/* tslint:disable */
/* eslint-disable */
/**
 * 訂餐系統
 * 系統API規格說明
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponderID
 */
export interface ResponderID {
    /**
     * 
     * @type {object}
     * @memberof ResponderID
     */
    Name?: object;
}

/**
 * Check if a given object implements the ResponderID interface.
 */
export function instanceOfResponderID(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ResponderIDFromJSON(json: any): ResponderID {
    return ResponderIDFromJSONTyped(json, false);
}

export function ResponderIDFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponderID {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'Name': !exists(json, 'Name') ? undefined : json['Name'],
    };
}

export function ResponderIDToJSON(value?: ResponderID | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Name': value.Name,
    };
}

