/* tslint:disable */
/* eslint-disable */
/**
 * 訂餐系統
 * 系統API規格說明
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponseTodayOrderModel
 */
export interface ResponseTodayOrderModel {
    /**
     * 
     * @type {string}
     * @memberof ResponseTodayOrderModel
     */
    OrderDetailID?: string;
    /**
     * 
     * @type {string}
     * @memberof ResponseTodayOrderModel
     */
    BrandName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ResponseTodayOrderModel
     */
    DrinkFoodName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ResponseTodayOrderModel
     */
    DetailRemark?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ResponseTodayOrderModel
     */
    DrinkFoodPrice?: number;
    /**
     * 
     * @type {number}
     * @memberof ResponseTodayOrderModel
     */
    Quantity?: number;
}

/**
 * Check if a given object implements the ResponseTodayOrderModel interface.
 */
export function instanceOfResponseTodayOrderModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ResponseTodayOrderModelFromJSON(json: any): ResponseTodayOrderModel {
    return ResponseTodayOrderModelFromJSONTyped(json, false);
}

export function ResponseTodayOrderModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseTodayOrderModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'OrderDetailID': !exists(json, 'OrderDetailID') ? undefined : json['OrderDetailID'],
        'BrandName': !exists(json, 'BrandName') ? undefined : json['BrandName'],
        'DrinkFoodName': !exists(json, 'DrinkFoodName') ? undefined : json['DrinkFoodName'],
        'DetailRemark': !exists(json, 'DetailRemark') ? undefined : json['DetailRemark'],
        'DrinkFoodPrice': !exists(json, 'DrinkFoodPrice') ? undefined : json['DrinkFoodPrice'],
        'Quantity': !exists(json, 'Quantity') ? undefined : json['Quantity'],
    };
}

export function ResponseTodayOrderModelToJSON(value?: ResponseTodayOrderModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'OrderDetailID': value.OrderDetailID,
        'BrandName': value.BrandName,
        'DrinkFoodName': value.DrinkFoodName,
        'DetailRemark': value.DetailRemark,
        'DrinkFoodPrice': value.DrinkFoodPrice,
        'Quantity': value.Quantity,
    };
}

