/* tslint:disable */
/* eslint-disable */
/**
 * 訂餐系統
 * 系統API規格說明
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { OptionsModel } from './OptionsModel';
import {
    OptionsModelFromJSON,
    OptionsModelFromJSONTyped,
    OptionsModelToJSON,
} from './OptionsModel';

/**
 * 
 * @export
 * @interface ResponseOrderDialogOptions
 */
export interface ResponseOrderDialogOptions {
    /**
     * 
     * @type {Array<OptionsModel>}
     * @memberof ResponseOrderDialogOptions
     */
    Office?: Array<OptionsModel> | null;
    /**
     * 
     * @type {Array<OptionsModel>}
     * @memberof ResponseOrderDialogOptions
     */
    Type?: Array<OptionsModel> | null;
    /**
     * 
     * @type {Array<OptionsModel>}
     * @memberof ResponseOrderDialogOptions
     */
    Store?: Array<OptionsModel> | null;
}

/**
 * Check if a given object implements the ResponseOrderDialogOptions interface.
 */
export function instanceOfResponseOrderDialogOptions(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ResponseOrderDialogOptionsFromJSON(json: any): ResponseOrderDialogOptions {
    return ResponseOrderDialogOptionsFromJSONTyped(json, false);
}

export function ResponseOrderDialogOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseOrderDialogOptions {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'Office': !exists(json, 'Office') ? undefined : (json['Office'] === null ? null : (json['Office'] as Array<any>).map(OptionsModelFromJSON)),
        'Type': !exists(json, 'Type') ? undefined : (json['Type'] === null ? null : (json['Type'] as Array<any>).map(OptionsModelFromJSON)),
        'Store': !exists(json, 'Store') ? undefined : (json['Store'] === null ? null : (json['Store'] as Array<any>).map(OptionsModelFromJSON)),
    };
}

export function ResponseOrderDialogOptionsToJSON(value?: ResponseOrderDialogOptions | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Office': value.Office === undefined ? undefined : (value.Office === null ? null : (value.Office as Array<any>).map(OptionsModelToJSON)),
        'Type': value.Type === undefined ? undefined : (value.Type === null ? null : (value.Type as Array<any>).map(OptionsModelToJSON)),
        'Store': value.Store === undefined ? undefined : (value.Store === null ? null : (value.Store as Array<any>).map(OptionsModelToJSON)),
    };
}

