/* tslint:disable */
/* eslint-disable */
/**
 * DrinkFood_API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponseModel
 */
export interface ResponseModel {
    /**
     * 
     * @type {number}
     * @memberof ResponseModel
     */
    Code?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ResponseModel
     */
    Success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ResponseModel
     */
    Message?: string | null;
}

/**
 * Check if a given object implements the ResponseModel interface.
 */
export function instanceOfResponseModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ResponseModelFromJSON(json: any): ResponseModel {
    return ResponseModelFromJSONTyped(json, false);
}

export function ResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'Code': !exists(json, 'Code') ? undefined : json['Code'],
        'Success': !exists(json, 'Success') ? undefined : json['Success'],
        'Message': !exists(json, 'Message') ? undefined : json['Message'],
    };
}

export function ResponseModelToJSON(value?: ResponseModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Code': value.Code,
        'Success': value.Success,
        'Message': value.Message,
    };
}

