/* tslint:disable */
/* eslint-disable */
/**
 * DrinkFood_API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponseLoginModel
 */
export interface ResponseLoginModel {
    /**
     * 
     * @type {string}
     * @memberof ResponseLoginModel
     */
    AccountID: string;
    /**
     * 
     * @type {string}
     * @memberof ResponseLoginModel
     */
    Token?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ResponseLoginModel
     */
    Name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ResponseLoginModel
     */
    Brief?: string | null;
}

/**
 * Check if a given object implements the ResponseLoginModel interface.
 */
export function instanceOfResponseLoginModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ResponseLoginModelFromJSON(json: any): ResponseLoginModel {
    return ResponseLoginModelFromJSONTyped(json, false);
}

export function ResponseLoginModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseLoginModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'AccountID': !exists(json, 'AccountID') ? undefined : json['AccountID'],
        'Token': !exists(json, 'Token') ? undefined : json['Token'],
        'Name': !exists(json, 'Name') ? undefined : json['Name'],
        'Brief': !exists(json, 'Brief') ? undefined : json['Brief'],
    };
}

export function ResponseLoginModelToJSON(value?: ResponseLoginModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'AccountID': value.AccountID,
        'Token': value.Token,
        'Name': value.Name,
        'Brief': value.Brief,
    };
}

