/* tslint:disable */
/* eslint-disable */
/**
 * DrinkFood_API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { OptionsModel } from './OptionsModel';
import {
    OptionsModelFromJSON,
    OptionsModelFromJSONTyped,
    OptionsModelToJSON,
} from './OptionsModel';

/**
 * 
 * @export
 * @interface ResponseProfileDialogOptions
 */
export interface ResponseProfileDialogOptions {
    /**
     * 
     * @type {Array<OptionsModel>}
     * @memberof ResponseProfileDialogOptions
     */
    LunchPayment: Array<OptionsModel>;
    /**
     * 
     * @type {Array<OptionsModel>}
     * @memberof ResponseProfileDialogOptions
     */
    DrinkPayment: Array<OptionsModel>;
}

/**
 * Check if a given object implements the ResponseProfileDialogOptions interface.
 */
export function instanceOfResponseProfileDialogOptions(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ResponseProfileDialogOptionsFromJSON(json: any): ResponseProfileDialogOptions {
    return ResponseProfileDialogOptionsFromJSONTyped(json, false);
}

export function ResponseProfileDialogOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseProfileDialogOptions {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'LunchPayment': (json['LunchPayment'] as Array<any>).map(OptionsModelFromJSON),
        'DrinkPayment': (json['DrinkPayment'] as Array<any>).map(OptionsModelFromJSON),
    };
}

export function ResponseProfileDialogOptionsToJSON(value?: ResponseProfileDialogOptions | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'LunchPayment': value.LunchPayment === undefined ? undefined : (value.LunchPayment === null ? null : (value.LunchPayment as Array<any>).map(OptionsModelToJSON)),
        'DrinkPayment': value.DrinkPayment === undefined ? undefined : (value.DrinkPayment === null ? null : (value.DrinkPayment as Array<any>).map(OptionsModelToJSON)),
    };
}

