/* tslint:disable */
/* eslint-disable */
/**
 * 訂餐系統
 * 系統API規格說明
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ViewDrinkFoodModel
 */
export interface ViewDrinkFoodModel {
    /**
     * 
     * @type {string}
     * @memberof ViewDrinkFoodModel
     */
    DrinkFoodID?: string;
    /**
     * 
     * @type {string}
     * @memberof ViewDrinkFoodModel
     */
    MenuID?: string;
    /**
     * 
     * @type {string}
     * @memberof ViewDrinkFoodModel
     */
    DrinkFoodName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ViewDrinkFoodModel
     */
    DrinkFoodTypeOrder?: number;
    /**
     * 
     * @type {string}
     * @memberof ViewDrinkFoodModel
     */
    DrinkFoodTypeID?: string;
    /**
     * 
     * @type {string}
     * @memberof ViewDrinkFoodModel
     */
    DrinkFoodTypeDesc?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ViewDrinkFoodModel
     */
    DrinkFoodPrice?: number;
    /**
     * 
     * @type {string}
     * @memberof ViewDrinkFoodModel
     */
    DrinkFoodRemark?: string | null;
}

/**
 * Check if a given object implements the ViewDrinkFoodModel interface.
 */
export function instanceOfViewDrinkFoodModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ViewDrinkFoodModelFromJSON(json: any): ViewDrinkFoodModel {
    return ViewDrinkFoodModelFromJSONTyped(json, false);
}

export function ViewDrinkFoodModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViewDrinkFoodModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'DrinkFoodID': !exists(json, 'DrinkFoodID') ? undefined : json['DrinkFoodID'],
        'MenuID': !exists(json, 'MenuID') ? undefined : json['MenuID'],
        'DrinkFoodName': !exists(json, 'DrinkFoodName') ? undefined : json['DrinkFoodName'],
        'DrinkFoodTypeOrder': !exists(json, 'DrinkFoodTypeOrder') ? undefined : json['DrinkFoodTypeOrder'],
        'DrinkFoodTypeID': !exists(json, 'DrinkFoodTypeID') ? undefined : json['DrinkFoodTypeID'],
        'DrinkFoodTypeDesc': !exists(json, 'DrinkFoodTypeDesc') ? undefined : json['DrinkFoodTypeDesc'],
        'DrinkFoodPrice': !exists(json, 'DrinkFoodPrice') ? undefined : json['DrinkFoodPrice'],
        'DrinkFoodRemark': !exists(json, 'DrinkFoodRemark') ? undefined : json['DrinkFoodRemark'],
    };
}

export function ViewDrinkFoodModelToJSON(value?: ViewDrinkFoodModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'DrinkFoodID': value.DrinkFoodID,
        'MenuID': value.MenuID,
        'DrinkFoodName': value.DrinkFoodName,
        'DrinkFoodTypeOrder': value.DrinkFoodTypeOrder,
        'DrinkFoodTypeID': value.DrinkFoodTypeID,
        'DrinkFoodTypeDesc': value.DrinkFoodTypeDesc,
        'DrinkFoodPrice': value.DrinkFoodPrice,
        'DrinkFoodRemark': value.DrinkFoodRemark,
    };
}

