/* tslint:disable */
/* eslint-disable */
/**
 * 訂餐系統
 * 系統API規格說明
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GroupOrderDetailModel } from './GroupOrderDetailModel';
import {
    GroupOrderDetailModelFromJSON,
    GroupOrderDetailModelFromJSONTyped,
    GroupOrderDetailModelToJSON,
} from './GroupOrderDetailModel';

/**
 * 
 * @export
 * @interface ViewOrderAndDetail
 */
export interface ViewOrderAndDetail {
    /**
     * 
     * @type {string}
     * @memberof ViewOrderAndDetail
     */
    OwnerName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ViewOrderAndDetail
     */
    OrderNo?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ViewOrderAndDetail
     */
    OrderStatusDesc?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ViewOrderAndDetail
     */
    OfficeName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ViewOrderAndDetail
     */
    ArrivalTime?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ViewOrderAndDetail
     */
    CloseTime?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ViewOrderAndDetail
     */
    CreateTime?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ViewOrderAndDetail
     */
    CanAdd?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ViewOrderAndDetail
     */
    CanClose?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ViewOrderAndDetail
     */
    DelayArrival?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ViewOrderAndDetail
     */
    DelayClose?: boolean;
    /**
     * 
     * @type {Array<GroupOrderDetailModel>}
     * @memberof ViewOrderAndDetail
     */
    Detail?: Array<GroupOrderDetailModel> | null;
}

/**
 * Check if a given object implements the ViewOrderAndDetail interface.
 */
export function instanceOfViewOrderAndDetail(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ViewOrderAndDetailFromJSON(json: any): ViewOrderAndDetail {
    return ViewOrderAndDetailFromJSONTyped(json, false);
}

export function ViewOrderAndDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViewOrderAndDetail {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'OwnerName': !exists(json, 'OwnerName') ? undefined : json['OwnerName'],
        'OrderNo': !exists(json, 'OrderNo') ? undefined : json['OrderNo'],
        'OrderStatusDesc': !exists(json, 'OrderStatusDesc') ? undefined : json['OrderStatusDesc'],
        'OfficeName': !exists(json, 'OfficeName') ? undefined : json['OfficeName'],
        'ArrivalTime': !exists(json, 'ArrivalTime') ? undefined : json['ArrivalTime'],
        'CloseTime': !exists(json, 'CloseTime') ? undefined : json['CloseTime'],
        'CreateTime': !exists(json, 'CreateTime') ? undefined : json['CreateTime'],
        'CanAdd': !exists(json, 'CanAdd') ? undefined : json['CanAdd'],
        'CanClose': !exists(json, 'CanClose') ? undefined : json['CanClose'],
        'DelayArrival': !exists(json, 'DelayArrival') ? undefined : json['DelayArrival'],
        'DelayClose': !exists(json, 'DelayClose') ? undefined : json['DelayClose'],
        'Detail': !exists(json, 'Detail') ? undefined : (json['Detail'] === null ? null : (json['Detail'] as Array<any>).map(GroupOrderDetailModelFromJSON)),
    };
}

export function ViewOrderAndDetailToJSON(value?: ViewOrderAndDetail | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'OwnerName': value.OwnerName,
        'OrderNo': value.OrderNo,
        'OrderStatusDesc': value.OrderStatusDesc,
        'OfficeName': value.OfficeName,
        'ArrivalTime': value.ArrivalTime,
        'CloseTime': value.CloseTime,
        'CreateTime': value.CreateTime,
        'CanAdd': value.CanAdd,
        'CanClose': value.CanClose,
        'DelayArrival': value.DelayArrival,
        'DelayClose': value.DelayClose,
        'Detail': value.Detail === undefined ? undefined : (value.Detail === null ? null : (value.Detail as Array<any>).map(GroupOrderDetailModelToJSON)),
    };
}

