/* tslint:disable */
/* eslint-disable */
/**
 * 訂餐系統
 * 系統API規格說明
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DerObjectIdentifier } from './DerObjectIdentifier';
import {
    DerObjectIdentifierFromJSON,
    DerObjectIdentifierFromJSONTyped,
    DerObjectIdentifierToJSON,
} from './DerObjectIdentifier';

/**
 * 
 * @export
 * @interface X509Extensions
 */
export interface X509Extensions {
    /**
     * 
     * @type {Array<DerObjectIdentifier>}
     * @memberof X509Extensions
     */
    readonly ExtensionOids?: Array<DerObjectIdentifier> | null;
}

/**
 * Check if a given object implements the X509Extensions interface.
 */
export function instanceOfX509Extensions(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function X509ExtensionsFromJSON(json: any): X509Extensions {
    return X509ExtensionsFromJSONTyped(json, false);
}

export function X509ExtensionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): X509Extensions {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ExtensionOids': !exists(json, 'ExtensionOids') ? undefined : (json['ExtensionOids'] === null ? null : (json['ExtensionOids'] as Array<any>).map(DerObjectIdentifierFromJSON)),
    };
}

export function X509ExtensionsToJSON(value?: X509Extensions | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}

